steps:
  build:
    image: docker:27-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t antost360/library-syncer --platform=linux/amd64 .
    when:
      - event: pull_request
