services:
  syncer:
    build: .
    restart: unless-stopped 
    environment:
      SONGS_PATH: /app/songs
      WORKER_COUNT: ${WORKER_COUNT}
      SLEEP_SEC: ${SLEEP_SEC}
    volumes:
      - type: bind
        source: ${DATA}
        target: /app/data
      - type: bind
        source: ${SONGS_PATH}
        target: /app/songs
