// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type IndexModel struct {
	TrackerListModel TrackerListModel
}

func Index(m IndexModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"mx-auto max-w-6xl px-6 py-10\"><header class=\"mb-10 flex items-end justify-between gap-6 border-b border-white/10 pb-6\"><div><h1 class=\"text-3xl\">Library Syncer</h1></div></header><section class=\"mb-10\"><div class=\"mb-4 flex items-center justify-between w-full gap-3\"><div class=\"flex flex-row gap-3 justify-center items-center\"><span class=\"inline-block h-2 w-2 rounded-full bg-[var(--accent)]\"></span><h2 class=\"font-display text-xl font-semibold text-white\">Active trackers</h2></div><button class=\"btn\" hx-post=\"/run\" hx-swap=\"none\">Trigger run <span class=\"htmx-indicator\">loading...</span></button></div><div hx-swap=\"innerHTML\" hx-get=\"/tracker-list\" hx-trigger=\"load, refreshList from:body, every 2s\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = TrackerList(m.TrackerListModel).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></section><section><div class=\"mb-4 flex items-center gap-3\"><span class=\"inline-block h-2 w-2 rounded-full bg-[var(--destructive)]\"></span><h2 class=\"font-display text-xl font-semibold text-white\">Add tracker</h2></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InsertTracker().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
